library(readr)
library(tidyverse)
library(lubridate)
library(ggplot2)

viol <- read.csv("prison_insp_viol_2010.csv", header = TRUE, stringsAsFactors = FALSE)
View(viol)
#Put data into documents and used this code

n_unique_names <- 
  viol %>% 
  select(estab_name) %>% 
  n_distinct()
  
n_unique_names

  
n_unique_keys1 <- 
  viol %>% 
  select(X.x) %>% 
  n_distinct()
  
n_unique_keys2 <- 
  viol %>% 
  select(activity_nr) %>% 
  n_distinct()
  
n_unique_keys1 == n_unique_keys2 

# I am guessing the X.x variable is used to correspond to the activity_nr variable. This is probably made by Savannah--good to know.

#I am interested in plotting the facility against the activity_nr somehow, as I think this will yield how many unique inspections facility does. I will try to figure that out.

unique_establ <- 
  viol %>% 
  select(estab_name) %>% 
  n_distinct()
unique_establ
#562 unique establishments


barplot(table(viol$estab_name))
#bar graph for unique establishment names with different associated violations

(table(viol$estab_name))
#Table for unique establishment names and different associated violations

colSums(sapply(viol, is.na))
#returns count for missingness of each variable; 2390 means there is no reported data for any

#Question: Why are some of the entries N/A and why are some of the entries just blank??

colSums(sapply(world_health_econ, is.na))
#Lab 4 is kind of hard to read compared to lab 5



