viol <- read.csv("prison_insp_viol_2010.csv", header = TRUE, stringsAsFactors = FALSE)
View(viol)
#uploading data


```{r}
library(tidyverse)
library(lubridate)
library(shiny)
library(shinydashboard)
```
#Loading the relevant libraries

unique_establ <- 
  viol %>% 
  select(estab_name) %>% 
  n_distinct()
unique_establ
#562 unique establishments



viol %>% group_by(site_state) %>% summarize(current_penalty_cost = sum(current_penalty, na.rm = TRUE), initial_penalty_cost = sum(initial_penalty, na.rm = TRUE)) %>% ungroup()
#Sorts penalty costs and initial costs by state

viol %>% group_by(estab_name) %>% summarize(current_penalty_cost = sum(current_penalty, na.rm = TRUE), initial_penalty_cost = sum(initial_penalty, na.rm = TRUE)) %>% ungroup()
#Sorts penaltry costs and initial costs by facility 

viol %>% 
  ggplot(aes(x = estab_name)) + 
  geom_bar() + 
  labs(title = "Inspections Per Facility", x = "Facility Name", y = "Unique Inspection Count")
  theme_bw() + 
   theme(text = element_text(size=4),
  axis.text.x = element_text(angle = 90))
#bar plot of number of unique inspections across all facilities
  
  
viol %>% 
  filter(site_state == "AZ") %>%
  ggplot(aes(x = estab_name)) + 
  geom_bar() + 
  labs(title = "Unqiue Inspections Per Facility in Arizona", x = "Facility Name", y = "Unique Inspection Count") +
  theme_bw()+
  theme(text = element_text(size=4),
  axis.text.x = element_text(angle = 90))
#say you want to zoom in on a specific condition e.g. you want to look at the unique inspections in Arizona, change the filter function; simply change the filter to an area of interest to zoom in on a specific variable condition

table(viol$estab_name)
#returns a table of all the establishment names and the number of inspections for each

viol %>% select(nr_in_estab) %>% summary()
#Brief statistical analysis of number of individuals in each establishment


viol %>% 
  ggplot(aes(x = estab_name, y = nr_exposed)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of Individuals Per Establishment", x = "Facility Name", y = "Number of Individuals") +
  theme_bw()+
  theme(text = element_text(size=4),
  axis.text.x = element_text(angle = 90))
#Represents the number of exposed individuals in each estabishment; can use filter to scrutinize as well

table(viol$year)
#Returns inspections based off year

#Let's dig deeper!! This is an excerpt I found: "In accordance with Section 17 of the OSH Act, OSHA takes into account the employer's size, good faith, previous history of violations, and the gravity of the violation when proposing penalties. Normally, a reduction of 60 percent may be applied to penalties if the employer has 25 employees or fewer; 40 percent if the employer has 26-100 employees; and 20 percent if the employer has 101-250 employees. Although no reduction for size is applied if an employer has more than 250 employees, the employer may still be accorded up to a 10 percent reduction for a lack of previous violations, and a 25 percent reduction for "good faith" which mainly depends upon the effectiveness of the employer's safety and health program. When these three factors are combined, it is possible for the smallest employers to receive up to a 95% reduction in the initial monetary penalty." From https://www.osha.gov/laws-regs/standardinterpretations/2001-05-04"

#“Gravity” as defined by the FOM as the severity of injury that could result from the alleged violation combined with the probability that an injury will occur.  For instances, it is more likely that an employee would fall from a steep sloped roof versus a flat roof, and more likely that they would be injured from a height of three stories versus one story. The FOM also breaks down levels of severity into four tiers, starting at “minimal” to “high” (death or permanent disability).   Probability is assessed by analyzing factors like the number of workers exposed to the condition, the proximity to the hazard, and the employee’s use of safety equipment, among other factors. It looks like we have to filter out certain factors though like spills.https://www.jimersonfirm.com/blog/2019/02/how-osha-calculates-penalties/"

#Idea: Let's try to explore gravity more in depth as a proxy for toxicity (we also need to filter out codes that are from non-toxic things like water spills). We can then do things like compare gravity to the violation fee to see if there is a correlation.

colSums(is.na(viol))
#1696 rows of 2390 rows are missing gravity ranking 



